//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Transactiondetails.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Account
    {
        public string FinancialYearCode { get; set; }
        public string AccountCode { get; set; }
        public string AccountID { get; set; }
        public string AccountName { get; set; }
        public Nullable<short> AccountGroupCode { get; set; }
        public Nullable<short> ExceptGroupCode { get; set; }
        public bool GroupCompany { get; set; }
        public string Relation { get; set; }
        public Nullable<double> OpeningBalance { get; set; }
        public Nullable<double> ClosingBalance { get; set; }
        public Nullable<short> CurrencyCode { get; set; }
        public string AccountAddress1 { get; set; }
        public string AccountAddress2 { get; set; }
        public string AccountAddress3 { get; set; }
        public string AccountPin { get; set; }
        public string AccountPhone { get; set; }
        public string AccountFax { get; set; }
        public string AccountResidencePhone { get; set; }
        public string AccountHandPhone { get; set; }
        public string AccountEMail { get; set; }
        public Nullable<decimal> InterestRate { get; set; }
        public string InterestMethod { get; set; }
        public string BankAccountName { get; set; }
        public string BankAccountNumber { get; set; }
        public string IncomeTaxNumber { get; set; }
        public string BranchCode { get; set; }
        public string AccountField1 { get; set; }
        public string AccountField2 { get; set; }
        public string AccountField3 { get; set; }
        public string AccountField4 { get; set; }
        public string AccountField5 { get; set; }
        public string ModuleID { get; set; }
        public Nullable<int> Table1Code { get; set; }
        public Nullable<int> Table2Code { get; set; }
        public string Suspended { get; set; }
        public Nullable<int> CityCode { get; set; }
        public Nullable<short> UserCode { get; set; }
        public Nullable<System.DateTime> EntryDate { get; set; }
        public Nullable<short> ModiUserCode { get; set; }
        public Nullable<System.DateTime> ModiDate { get; set; }
        public Nullable<int> Field1 { get; set; }
        public Nullable<int> Field2 { get; set; }
        public string AccountField6 { get; set; }
        public string AccountField7 { get; set; }
        public string AccountField8 { get; set; }
        public string AccountField9 { get; set; }
        public string AccountField10 { get; set; }
        public string Transfer { get; set; }
    }
}
