//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Transactiondetails.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CSystem1
    {
        public short ModuleCode { get; set; }
        public string ModuleName { get; set; }
        public string ModuleID { get; set; }
        public string ModuleType { get; set; }
        public string ModuleCategory { get; set; }
        public string PreModuleID { get; set; }
        public Nullable<int> FieldID { get; set; }
        public bool EnableFlag { get; set; }
        public Nullable<byte> OrderNumber { get; set; }
        public bool IncludeInFlow { get; set; }
        public byte AuthorisationFlag { get; set; }
        public Nullable<byte> AuthorisationLevel { get; set; }
        public bool HFlag { get; set; }
        public bool FFlag { get; set; }
        public bool AFlag { get; set; }
        public bool PFlag { get; set; }
        public string MenuId { get; set; }
        public string ReferenceNumber { get; set; }
        public string AmountField { get; set; }
        public bool OptionalFlag { get; set; }
        public bool DFlag { get; set; }
        public bool AddModeFlag { get; set; }
    }
}
