//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Transactiondetails.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CSystem2
    {
        public string TableID { get; set; }
        public string TableName { get; set; }
        public string Type { get; set; }
        public string TableDescription { get; set; }
    }
}
