//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Transactiondetails.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CSystem3
    {
        public string TableID { get; set; }
        public int FieldID { get; set; }
        public string Type { get; set; }
        public string FieldName { get; set; }
        public string Caption { get; set; }
        public Nullable<byte> Size { get; set; }
        public string DefaultValue { get; set; }
        public bool Must { get; set; }
        public string LinkTableID { get; set; }
        public Nullable<int> LinkFieldID { get; set; }
        public bool Required { get; set; }
        public bool UDFieldFlag { get; set; }
        public string UDFieldType { get; set; }
        public bool CaptionChangeFlag { get; set; }
        public string Remarks { get; set; }
    }
}
