//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Transactiondetails.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustGroup
    {
        public short CustomerGroupCode { get; set; }
        public string CustomerGroupName { get; set; }
        public string OwnerName { get; set; }
        public string ContactPersonName { get; set; }
        public string ReferenceName { get; set; }
        public Nullable<double> CreditLimit { get; set; }
        public bool Suspended { get; set; }
        public string Remarks { get; set; }
        public Nullable<short> UserCode { get; set; }
        public Nullable<System.DateTime> EntryDate { get; set; }
        public Nullable<short> ModiUserCode { get; set; }
        public Nullable<System.DateTime> ModiDate { get; set; }
    }
}
