//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Transactiondetails.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Install
    {
        public short SerialNumber { get; set; }
        public string ModuleCode { get; set; }
        public string ModuleDescription { get; set; }
        public string Password { get; set; }
    }
}
