//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Transactiondetails.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ItemMaster
    {
        public int ItemCode { get; set; }
        public string ItemName { get; set; }
        public string ItemDescription { get; set; }
        public Nullable<short> ItemCategoryCode { get; set; }
        public string ItemUnit { get; set; }
        public Nullable<double> MinimumStock { get; set; }
        public Nullable<double> PurchaseRate { get; set; }
        public Nullable<double> SaleRate { get; set; }
        public string Remarks { get; set; }
        public bool DeletedFlag { get; set; }
        public Nullable<short> UserCode { get; set; }
        public Nullable<System.DateTime> EntryDate { get; set; }
        public Nullable<short> ModiUserCode { get; set; }
        public Nullable<System.DateTime> ModiDate { get; set; }
    
        public virtual ItemCategory ItemCategory { get; set; }
    }
}
