//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Transactiondetails.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class JobBillingMa
    {
        public int SerialNumber { get; set; }
        public string ProcessingPointCode { get; set; }
        public string FinancialYearCode { get; set; }
        public string BranchCode { get; set; }
        public string AccountCode { get; set; }
        public Nullable<System.DateTime> ReferenceDate { get; set; }
        public string Remarks { get; set; }
        public string ReferenceNumber { get; set; }
        public Nullable<int> LedSerialNumber { get; set; }
        public string SaleAccountCode { get; set; }
        public Nullable<short> CreditDays { get; set; }
        public Nullable<System.DateTime> PostingDate { get; set; }
        public Nullable<double> PostingAmount { get; set; }
        public Nullable<double> PostingAmount2 { get; set; }
        public Nullable<bool> DeletedFlag { get; set; }
        public Nullable<short> UserCode { get; set; }
        public Nullable<System.DateTime> EntryDate { get; set; }
        public Nullable<short> ModiUserCode { get; set; }
        public Nullable<System.DateTime> ModiDate { get; set; }
        public string ReferenceType { get; set; }
        public Nullable<double> Addless1 { get; set; }
        public Nullable<double> Addless2 { get; set; }
        public Nullable<double> Addless3 { get; set; }
        public Nullable<double> PostingAmount3 { get; set; }
        public Nullable<double> RoundedAmount { get; set; }
        public Nullable<double> FinalAmount { get; set; }
    }
}
