//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Transactiondetails.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class JobBillingDet
    {
        public int SerialNumber { get; set; }
        public short ItemSerialNumber { get; set; }
        public int JDSerialNumber { get; set; }
        public short JDItemSerialNumber { get; set; }
        public Nullable<double> BillingQuantity { get; set; }
        public Nullable<double> NoChargeQuantity { get; set; }
        public string BillingType { get; set; }
        public Nullable<double> BillingRate { get; set; }
        public string BankCashFlag { get; set; }
        public Nullable<double> TotalAmount { get; set; }
        public string DiscountPerAmt { get; set; }
        public Nullable<double> DiscountRate { get; set; }
        public Nullable<double> DiscountAmount { get; set; }
        public Nullable<double> BillingAmount { get; set; }
        public string Remarks { get; set; }
        public Nullable<double> Addless1 { get; set; }
        public Nullable<double> Addless2 { get; set; }
        public Nullable<double> Addless3 { get; set; }
        public Nullable<double> NetAmount { get; set; }
    }
}
