//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Transactiondetails.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class JobReceiptDet
    {
        public int SerialNumber { get; set; }
        public short ItemSerialNumber { get; set; }
        public short ProcessCode { get; set; }
        public short PacketNumber { get; set; }
        public Nullable<double> ItemPieces { get; set; }
        public Nullable<double> ItemCarats { get; set; }
        public Nullable<double> ItemLines { get; set; }
        public Nullable<bool> ReWorkingFlag { get; set; }
        public string Remarks { get; set; }
        public Nullable<double> BillingRate { get; set; }
        public Nullable<double> BillingQuantity { get; set; }
    }
}
