//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Transactiondetails.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ParameterSetting
    {
        public string CompanyCode { get; set; }
        public string PurchaseAccountCode { get; set; }
        public string SaleAccountCode { get; set; }
        public Nullable<bool> StockCheckFlag { get; set; }
    }
}
