//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Transactiondetails.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProcessDet
    {
        public short ProcessCode { get; set; }
        public short SerialNumber { get; set; }
        public Nullable<double> RangeFrom { get; set; }
        public Nullable<double> RangeTo { get; set; }
        public Nullable<double> BillingRate { get; set; }
    }
}
