//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Transactiondetails.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class System12
    {
        public int ReportID { get; set; }
        public byte ReportSubID { get; set; }
        public short ObjectID { get; set; }
        public short PropertyID { get; set; }
        public byte ObjectType { get; set; }
        public Nullable<byte> BandNo { get; set; }
        public string PropertyValue { get; set; }
    }
}
