//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Transactiondetails.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class System2
    {
        public short CategoryCode { get; set; }
        public string ModuleID { get; set; }
        public string Access { get; set; }
        public Nullable<byte> Days { get; set; }
    }
}
