//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Transactiondetails.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class System3
    {
        public int Field1 { get; set; }
        public string Field2 { get; set; }
        public string Field3 { get; set; }
        public string Field4 { get; set; }
        public Nullable<int> Field5 { get; set; }
        public string Field6 { get; set; }
        public string Field7 { get; set; }
        public string Password { get; set; }
        public string EmailId { get; set; }
        public Nullable<bool> Active { get; set; }
        public Nullable<int> CityCode { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
    }
}
