//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Transactiondetails.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class System5
    {
        public string ProcessingPointCode { get; set; }
        public string ProcessingPointName { get; set; }
        public string NameOfServer { get; set; }
        public string IPAddress { get; set; }
        public string CurrentServerFlag { get; set; }
        public string MktgProcessingPointCode { get; set; }
        public string MailHost { get; set; }
        public Nullable<short> MailPort { get; set; }
    }
}
