//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Transactiondetails.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class System9
    {
        public string CompanyCode { get; set; }
        public string ModuleID { get; set; }
        public byte LevelNumber { get; set; }
        public short UserCode { get; set; }
        public Nullable<double> AmountMinimum { get; set; }
        public Nullable<double> AmountMaximum { get; set; }
        public Nullable<byte> WithInDays { get; set; }
        public string UserId { get; set; }
    }
}
