//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Transactiondetails.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class System16
    {
        public short FormTag { get; set; }
        public short ObjectTag { get; set; }
        public string ObjectName { get; set; }
        public string ObjectCaption { get; set; }
        public string ObjectHint { get; set; }
        public bool ObjectChangeFont { get; set; }
        public Nullable<int> PickListCode { get; set; }
        public bool EnablePickList { get; set; }
    }
}
