//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Transactiondetails.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class System8
    {
        public string CompanyCode { get; set; }
        public int SrNo { get; set; }
        public Nullable<short> UserCode { get; set; }
        public Nullable<System.DateTime> MsgDate { get; set; }
        public string ModuleId { get; set; }
        public string Message { get; set; }
        public Nullable<short> FromUserCode { get; set; }
        public string RefNo { get; set; }
        public bool MsgStatus { get; set; }
        public Nullable<double> RefAmount { get; set; }
    }
}
