//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Transactiondetails.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class System11
    {
        public int ReportID { get; set; }
        public byte ReportSubID { get; set; }
        public string ReportName { get; set; }
        public string ReportDesc { get; set; }
        public byte ReportType { get; set; }
        public bool BaseTitle { get; set; }
        public bool BasePageHeader { get; set; }
        public bool BasePageFooter { get; set; }
        public bool ReportLocked { get; set; }
    }
}
