//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Transactiondetails.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TDSFile
    {
        public string FinancialYearCode { get; set; }
        public string ProcessingPointCode { get; set; }
        public int LedSerialNumber { get; set; }
        public short LedSubNumber { get; set; }
        public string AccountCode { get; set; }
        public string ITaxCode { get; set; }
        public Nullable<System.DateTime> TaxDate { get; set; }
        public Nullable<double> TaxOn { get; set; }
        public Nullable<double> TaxRate { get; set; }
        public Nullable<double> TaxValue { get; set; }
        public string TaxType { get; set; }
        public string Flag { get; set; }
        public string CertYearCode { get; set; }
        public string CertPPCode { get; set; }
        public Nullable<int> CertificateSrNo { get; set; }
        public string ChallanNo { get; set; }
        public Nullable<System.DateTime> ChallanDate { get; set; }
        public string Bank { get; set; }
        public string ReferenceNumber { get; set; }
        public string PayFlag { get; set; }
        public string PayYearCode { get; set; }
        public string PayPPCode { get; set; }
        public Nullable<int> PaySrNo { get; set; }
    }
}
