//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Transactiondetails.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TDSPaymentMaster
    {
        public string FinancialYearCode { get; set; }
        public string ProcessingPointCode { get; set; }
        public int PaySerialNumber { get; set; }
        public string ReferenceNumber { get; set; }
        public Nullable<System.DateTime> ReferenceDate { get; set; }
        public string Prefix { get; set; }
        public string Separator { get; set; }
        public Nullable<int> Number { get; set; }
        public string Suffix { get; set; }
        public string Nature { get; set; }
        public Nullable<double> Amount { get; set; }
        public string ITaxCode { get; set; }
        public string ChallanNo { get; set; }
        public Nullable<System.DateTime> ChallanDate { get; set; }
        public string Bank { get; set; }
        public Nullable<int> PaymentLedSerialNumber { get; set; }
        public string PaymentPPCode { get; set; }
        public string AuthorizationStatus1 { get; set; }
        public Nullable<byte> AuthorisedBy1 { get; set; }
        public string AuthorizationStatus2 { get; set; }
        public Nullable<byte> AuthorisedBy2 { get; set; }
        public string ModuleID { get; set; }
        public Nullable<short> UserCode { get; set; }
        public Nullable<System.DateTime> EntryDate { get; set; }
        public Nullable<short> ModiUserCode { get; set; }
        public Nullable<System.DateTime> ModiDate { get; set; }
    }
}
